# -*- coding: utf-8 -*-
"""ScriptModeleMeteo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NuIXzbqqxr5uo-ZEgsMSomcCIREFIngZ

# Création de deux modèles pour la prédiction de pluie ainsi que de la quantité de pluie attendue

## Modèle 1 : Prédiction pluie

Imports des bibliothèque nécessaires pour l'entrainement et la création du modèle
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import classification_report, accuracy_score, mean_squared_error, r2_score

"""Chargement du jeux de données"""

df = pd.read_csv('synop_2026.csv', sep=';')  # Adaptez le séparateur si nécessaire
print("Données chargées avec succès !")

"""Converstion du champ pour extraire le mois et l'heure"""

df['validity_time'] = pd.to_datetime(df['validity_time'])
df['month'] = df['validity_time'].dt.month
df['hour'] = df['validity_time'].dt.hour

"""Sélectionne des caractéristiques utiles pour l'entrainement ainsi que du champ qu'on va essayer de prédire"""

features = ['t', 'u', 'pmer', 'tend', 'ff', 'n', 'month', 'hour']
target_precipitation = 'rr3'

"""Gestion des valeurs manquantes (on remplace par la médiane)"""

for col in features + [target_precipitation]:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].median())

"""Création d'un cible binaire pour la classification (Pas de pluie = 0 , Pluie = 1)"""

df['is_raining'] = (df[target_precipitation] > 0.1).astype(int)
X = df[features]
y_class = df['is_raining']          # Cible Classification
y_reg = df[target_precipitation]    # Cible Régression (quantité de pluie)

"""Division des données en un ensembles d'entrainement et de test (80/20)"""

X_train, X_test, y_train_class, y_test_class = train_test_split(X, y_class, test_size=0.2, random_state=42)
_, _, y_train_reg, y_test_reg = train_test_split(X, y_reg, test_size=0.2, random_state=42)

"""Normalisation des données"""

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""Entrainement du modèle de classification via le modèle d'arbre de foret"""

clf = RandomForestClassifier(n_estimators=100, class_weight='balanced_subsample', random_state=42)
clf.fit(X_train_scaled, y_train_class)

"""Mise en avant des variables servant à évaluer le modèle"""

# Évaluation du classifieur
y_pred_class = clf.predict(X_test_scaled)
print(f"Précision globale (Accuracy) : {accuracy_score(y_test_class, y_pred_class):.2%}")
print("\nRapport de classification :")
print(classification_report(y_test_class, y_pred_class, target_names=['Pas de pluie', 'Pluie']))

"""##Modèle 2 : Régression pour déterminer la quantité de pluie
On va utiliser les données normalisées pour essayer d'avoir plus de précision sur la prédiction
"""

reg = RandomForestRegressor(n_estimators=100, random_state=42)
reg.fit(X_train_scaled, y_train_reg)

"""Mise en avant de l'évaluation du deuxième modèle"""

y_pred_reg = reg.predict(X_test_scaled)
y_pred_reg = np.clip(y_pred_reg, 0, None)
mse = mean_squared_error(y_test_reg, y_pred_reg)
r2 = r2_score(y_test_reg, y_pred_reg)
print(f"Erreur Quadratique Moyenne (MSE) : {mse:.4f} mm")
print(f"Coefficient de détermination (R²) : {r2:.4f}")

"""##Mise à disposition des modèles pour utilisation dans l'API"""

import joblib

joblib.dump(clf, 'modele_classification.joblib')
joblib.dump(reg, 'modele_regression.joblib')